apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
  labels:
    appp: nginx
    type: front-end
spec:
  replicas: 2
  template:
    metadata:
      name: ngxinx-pod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
    
   