apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: voting-app
spec:
  containers:
    - name: worker-pod
      image: kodekloud/examplevotingapp_worker:v1
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"